name: "Generate References"

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
  workflow_dispatch:

jobs:
  docs-generation:
    name: Generate references
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          fetch-depth: 0
          token: ${{ secrets.POSTHOG_BOT_PAT }}

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
        with:
          python-version: 3.11.11

      - name: Install uv
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
        with:
            enable-cache: true
            pyproject-file: 'pyproject.toml'

      - name: Generate references
        run: |
          uv run bin/docs generate-references

      - name: Check for changes in references
        id: changes
        run: |
          if [ -n "$(git status --porcelain references/)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "New references generated in references directory:"
            git status --porcelain references/
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No new references generated in references directory"
          fi

      - uses: stefanzweifel/git-auto-commit-action@b3e3f72439fc3af08948f989a19a825463598a
        if: steps.changes.outputs.changed == 'true'
        with:
          commit_message: "Update generated references"
          file_pattern: references/