name: "Generate References"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docs-generation:
    name: Generate references
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.POSTHOG_BOT_GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.11

      - name: Install uv
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
        with:
            enable-cache: true
            pyproject-file: 'pyproject.toml'

      - name: Generate references
        run: |
          uv run bin/docs generate-references

      - name: Check for changes in references
        id: changes
        run: |
          if [ -n "$(git status --porcelain references/)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "New references generated in references directory:"
            git status --porcelain references/
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No new references generated in references directory"
          fi

      - uses: stefanzweifel/git-auto-commit-action@v6
        if: steps.changes.outputs.changed == 'true'
        with:
          commit_message: "Update generated references"
          file_pattern: references/